#! /bin/sh

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1-0')
if [[ $my_laptop_external_monitor = *connected* ]]; 
then
  sleep 1
  # xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --rate 144 --output VIRTUAL1 --off --output DP-1-0 --off --output DP-1-1 --off --output HDMI-1-0 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-1-2 --off --output DP-1-3 --off --output DP-1-4 --off --output DP-1-5 --off
  # xrandr --output eDP1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output VIRTUAL1 --off --output DP-1-0 --off --output DP-1-1 --off --output HDMI-1-0 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1-2 --off --output DP-1-3 --off --output DP-1-4 --off --output DP-1-5 --off
  xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off --output DP-1-0 --off --output DP-1-1 --off --output HDMI-1-0 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-1-2 --off --output DP-1-3 --off --output DP-1-4 --off --output DP-1-5 --off

else
  xrandr --output eDP1 --mode 1920x1080 --rotate normal --rate 144 
fi

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a xdman-Main state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Tk state=floating
bspc rule -a Spotify desktop='^10' state=floating


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart

# Bar
/home/termanteus/Downloads/apps/etc/another_dotfiles/polybar/launch.sh &
# Notifications
/home/termanteus/.config/dunst/launch.sh
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
# nitrogen --restore &
nitrogen --force-setter=xinerama --restore &
# # Dex
dex -a -s /etc/xdg/autostart:~/.config/autostart/
# Picom
picom &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# # cava for polybar
# cava -p ~/.config/cava/polybar.conf &
